#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=04:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2
module load CUDA/12.1.1

cd $HOME/Wan2.1/
source activate fomo
#pip install torch torchvision torchaudio
#pip install -r requirements.txt
pip install "huggingface_hub[cli]"
pip install "xfuser>=0.4.1"